logging:
  pattern:
# Ohne Datum/Uhrzeit, besser fuer Video-Demo
#    console: "%magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    de.trion.training: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        exposed-headers: "*"
        allowed-methods: GET, POST, OPTIONS
        allow-credentials: "true"
        allowed-origin-patterns: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

spring:
  data:
    web:
      pageable:
        default-page-size: 4
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  datasource:
#    url: jdbc:mariadb://localhost/training
#    username: root
#    password: training

info:
  sample: from info
  jvm:
    version: ${java.specification.version}
    vendor: ${java.specification.vendor}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev-migration
---
spring:
  config:
    activate:
      on-profile: mariadb

  datasource:
    url: jdbc:mariadb://localhost/app
    username: app
    password: app

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev-migration
